import { JobsList } from '@/libs/definitions';

export const jobsMockData: JobsList = {
  '30302425-44ca-466a-ae37-87a5039d73ee': {
    id: 2,
    portal: 'workday',
    title: 'NodeJs Developer',
    workplace_type: null,
    posted_date: '2025-02-01',
    job_state: null,
    description:
      "Required Skills & Experience Experience developing and deploying web application backends in NodeJS and JavaScript to support a RESTful microservices architectureNestJS experience- Deep level of proficiency with Docker, JavaScript/TypeScript, and server-side NodeJS- Strong experience building REST APIs and integrating them with frontend technologies- Experience migrating APIs from application gateways to self-hosted solutions- Ability to modify and/or support enterprise applications and data- Experience with document-based NoSQL databases like MongoDB- Great communication skills -- must have desire/comfortability training more junior developers! Nice to Have Skills & Experience Certification in a technology specific domain (Cloud Architecture, Security, etc.)- Experience with implementing backend APIs in Java / Spring Boot- Previous experience working with insurance related applications- Bachelors or master's degree in computer science or related field of study- Hands-on experience with Axway application gatewayhas context menu",
    apply_link: null,
    company_name: null,
    location: null,
    short_description: null,
    field: null,
    company_logo: null,
    experience: null,
    skills_required: null,
  },
  '479b1aee-ca9c-48b1-8ff2-8f1f7c379894': {
    id: 12345,
    portal: 'workday',
    title: 'Senior Software Engineer',
    workplace_type: 'remote',
    posted_date: '2025-01-02',
    job_state: 'open',
    description:
      'We are seeking a Senior Software Engineer to develop high-quality software solutions.',
    apply_link: 'https://example.com/job/12345/apply',
    company_name: 'TechCorp',
    location: 'San Francisco, CA',
    short_description: 'Exciting role at a fast-growing tech company.',
    field: 'Technology',
    company_logo: 'https://example.com/assets/logos/techcorp.png',
    experience: '5+ years of experience',
    skills_required: ['Python', 'Docker', 'Kubernetes', 'AWS'],
  },
  '900d7249-310d-475d-8527-f06fd552cd3d': {
    id: 21,
    portal: 'workday',
    title: 'FP&A manager',
    workplace_type: null,
    posted_date: null,
    job_state: '2024-01-01',
    description: 'Boh',
    apply_link: null,
    company_name: null,
    location: null,
    short_description: null,
    field: null,
    company_logo: null,
    experience: null,
    skills_required: null,
  },
  'e32b9819-5a43-450a-aacb-799182572db1': {
    id: 1,
    portal: 'workday',
    title: 'FP&A manager (mock data)',
    workplace_type: null,
    posted_date: '2024-12-01',
    job_state: null,
    description: 'Boh',
    apply_link: null,
    company_name: null,
    location: null,
    short_description: null,
    field: null,
    company_logo: null,
    experience: null,
    skills_required: null,
  },
};

export const failedJobsMockData: JobsList = {
  'e32b9819-5a43-450a-aacb-799182572db1': {
    id: 12345,
    portal: 'workday',
    title: 'Senior Software Engineer (failed mock data)',
    workplace_type: 'remote',
    posted_date: '2025-01-01',
    job_state: 'open',
    description:
      'We are seeking a Senior Software Engineer to develop high-quality software solutions.',
    apply_link: 'https://example.com/job/12345/apply',
    company_name: 'TechCorp',
    location: 'San Francisco, CA',
    short_description: 'Exciting role at a fast-growing tech company.',
    field: 'Technology',
    company_logo: 'https://example.com/assets/logos/techcorp.png',
    experience: '5+ years of experience',
    skills_required: ['Python', 'Docker', 'Kubernetes', 'AWS'],
  },
};
