import { TemplateStyle } from "@/libs/types/cv-template-style.type";

export const style_2: TemplateStyle = {
  body: 'font-liberation-sans leading-[1.2] text-[#333] max-w-[700px] mx-auto px-[10px] py-0 text-[10pt] flex flex-col',
  personal: {
    header: 'text-center mb-[20px] order-0',
    h1: 'text-[21pt] leading-[1] font-medium mb-[8px]',
    contactSection: 'flex flex justify-center flex-wrap font-normal',
    contactItem: '[&:first-child:before]:content-["+"] [&:not(:first-child):before]:content-["|"] [&:not(:first-child):before]:mx-[4px]',
  },
  education: {
    container: 'order-2',
    h2: 'text-[11pt] font-bold uppercase border-b-2 border-solid border-[#333] mb-[12px] pb-[3px] text-left',
    entry: 'mb-[8px]',
    entryHeader: 'flex justify-between mb-[3px]',
    entryDetails: 'flex justify-between gap-5 mb-[4px]',
    coursesDetails: 'mb-[3px]',
    entryName: 'font-bold',
    entryLocation: 'shrink-0',
    entryYear: 'italic shrink-0',
    compactList: 'list-disc pb-[6px] pl-[36px]',
    listItem: 'mb-[2px]',
  },
  experience: {
    container: 'order-1',
    h2: 'text-[11pt] font-bold uppercase border-b-2 border-solid border-[#333] mb-[12px] pb-[3px] text-left',
    entry: 'mb-[8px]',
    entryHeader: 'flex justify-between mb-[3px]',
    entryDetails: 'flex justify-between gap-5 mb-[4px]',
    entryName: 'font-bold',
    entryLocation: 'shrink-0',
    entryYear: 'italic shrink-0',
    compactList: 'list-disc pb-[6px] pl-[36px]',
    listItem: 'mb-[2px]',
  },
  projects: {
    container: 'order-3',
    h2: 'text-[11pt] font-bold uppercase border-b-2 border-solid border-[#333] mb-[12px] pb-[3px] text-left',
    entry: 'mb-[8px]',
    entryHeader: 'flex gap-1 mb-[3px]',
    entryName: 'font-bold',
    compactList: 'list-disc pb-[6px] pl-[36px]',
    listItem: 'mb-[2px]',
  },
  additional: {
    container: '',
    h2: 'text-[11pt] font-bold uppercase border-b-2 border-solid border-[#333] mb-[12px] pb-[3px] text-left',
    h3: 'text-[10pt] font-bold uppercase mt-[8px] mb-[4px] text-left',
    compactList: 'list-disc pb-[6px] pl-[36px]',
    listItem: 'mb-[2px]',
  },
};