import { TemplateStyle } from "@/libs/types/cv-template-style.type";

export const style_3: TemplateStyle = {
  body: 'font-liberation-serif leading-[1.2] text-[#333] max-w-[700px] mx-auto px-[20px] py-[10px] text-[10pt] flex flex-col',
  personal: {
    header: 'text-center mb-[20px] order-0',
    h1: 'text-[25pt] leading-[1] font-bold mb-[7px]',
    contactSection: 'flex flex justify-center flex-wrap font-normal',
    contactItem: '[&:not(:first-child):before]:content-["|"] [&:not(:first-child):before]:mx-[5px]',
  },
  education: {
    container: 'order-1',
    h2: 'text-[12pt] font-bold uppercase border-b border-solid border-[#333] mb-[10px] text-left',
    entry: 'mb-[10px]',
    entryHeader: 'flex mb-[3px]',
    entryDetails: 'flex justify-between gap-5 mb-[4px]',
    coursesDetails: 'mb-[3px]',
    entryTitle: 'font-bold',
    entryName: 'font-bold',
    entryLocation: 'shrink-0 italic before:content-["-"] before:mx-[4px]',
    entryYear: 'shrink-0 -mt-[19px]',
    compactList: 'list-disc pl-[15px]',
    listItem: 'mb-[2px]',
  },
  experience: {
    container: 'order-2',
    h2: 'text-[12pt] font-bold uppercase border-b border-solid border-[#333] mb-[10px] text-left',
    entry: 'mb-[10px]',
    entryHeader: 'flex mb-[3px]',
    entryDetails: 'flex justify-between gap-5 mb-[4px]',
    entryTitle: 'font-bold',
    entryName: 'font-bold',
    entryLocation: 'shrink-0 italic before:content-["-"] before:mx-[4px]',
    entryYear: 'shrink-0 -mt-[19px]',
    compactList: 'list-disc pl-[15px]',
    listItem: 'mb-[2px]',
  },
  projects: {
    container: 'order-3',
    h2: 'text-[12pt] font-bold uppercase border-b border-solid border-[#333] mb-[10px] text-left',
    entry: 'mb-[10px]',
    entryHeader: 'flex gap-1 mb-[3px]',
    entryName: 'font-bold',
    compactList: 'list-disc pl-[15px]',
    listItem: 'mb-[2px]',
  },
  additional: {
    container: '',
    h2: 'text-[12pt] font-bold uppercase border-b border-solid border-[#333] mb-[10px] text-left',
    h3: 'text-[11pt] font-bold uppercase mt-[10px] mb-[4px] text-left',
    compactList: 'list-disc pl-[15px]',
    listItem: 'mb-[2px]',
  },
};